# Generated by Django 3.2.9 on 2021-11-15 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0002_auto_20211115_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points_spent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Points_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_product_id', models.CharField(max_length=255, null=True)),
                ('google_product_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('points', models.DecimalField(decimal_places=0, max_digits=15)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'Tipping'), (2, 'Tipped')], default=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='User_stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal')], default=1)),
                ('deposit_reason', models.IntegerField(choices=[(1, 'Participation in a performance'), (2, 'Application of a stamp code')], null=True)),
                ('withdrawal_reason', models.IntegerField(choices=[(1, 'Exchange for a ticket')], null=True)),
                ('stamps', models.DecimalField(decimal_places=0, max_digits=15)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('stamps_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal')], default=1)),
                ('deposit_reason', models.IntegerField(choices=[(1, 'Purchase')], null=True)),
                ('withdrawal_reason', models.IntegerField(choices=[(1, 'Exchange for a gift'), (2, 'Exchange for a ticket')], null=True)),
                ('points', models.DecimalField(decimal_places=0, max_digits=15)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('points_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Unused'), (1, 'Used')], default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.gift')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stamps_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('stamps_granted', models.DecimalField(decimal_places=0, max_digits=15)),
                ('number_of_applicable_user', models.IntegerField(null=True)),
                ('number_of_applied_user', models.IntegerField()),
                ('expires_in', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('target_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ranking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.ranking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Points_package_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('purchased_at', models.DateField(auto_now_add=True)),
                ('apple_trans_id', models.CharField(max_length=255, null=True)),
                ('google_trans_id', models.CharField(max_length=255, null=True)),
                ('apple_receipt', models.TextField(null=True)),
                ('google_receipt', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.points_package')),
                ('user_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_point')),
            ],
        ),
        migrations.CreateModel(
            name='Point_spending_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_gift')),
                ('user_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_point')),
            ],
        ),
        migrations.CreateModel(
            name='Gift_purchase_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_gift')),
                ('user_point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_point')),
            ],
        ),
    ]
