# Generated by Django 3.2.9 on 2021-11-15 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0001_initial'),
        ('Point', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift_tipping_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_equivalent', models.DecimalField(decimal_places=0, max_digits=15)),
                ('tipped_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterData.box_notification_trans_content')),
                ('user_gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_gift')),
            ],
        ),
    ]
