# Generated by Django 3.2.9 on 2021-11-15 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0002_auto_20211115_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Live stream event'), (2, 'Office event')])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_private', models.IntegerField(choices=[(0, 'Not private'), (1, 'Private')], default=1)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('is_archived', models.IntegerField(choices=[(0, 'Not archived'), (1, 'Archived')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('streaming_method', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(null=True)),
                ('ticket_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.events')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('points_required', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('expiration_datetime', models.DateTimeField(auto_now_add=True)),
                ('drawing_flag', models.SmallIntegerField(choices=[(0, 'No drawing'), (1, 'By drawing')], default=1)),
                ('drawing_application_deadline', models.DateTimeField(auto_now_add=True, null=True)),
                ('drawing_status', models.SmallIntegerField(choices=[(0, 'Drawing preiod'), (1, ' Purchase method')], default=1)),
                ('stamp_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('max_number_of_ticket', models.IntegerField()),
                ('number_of_issued_tickets', models.IntegerField()),
                ('is_seat_id_assigned', models.SmallIntegerField(choices=[(0, 'Not assigned'), (1, 'Assigned')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.performance')),
            ],
        ),
        migrations.CreateModel(
            name='User_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
                ('is_settled', models.IntegerField(choices=[(0, 'Unsettled'), (1, 'Settled')], default=1)),
                ('seat_id', models.CharField(max_length=255, null=True)),
                ('expire_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Unused'), (1, 'Used')], default=1)),
                ('used_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_purchase_revervation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, null=True)),
                ('number_of_tickets', models.IntegerField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('is_purchased', models.SmallIntegerField(choices=[(0, 'Not purchased'), (1, 'Purchased')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.ticket')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_purchase_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('point_amount', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('payment_type', models.CharField(choices=[('card', 'Credit card'), ('cvs', 'Convenience store payment')], max_length=25, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('settle_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('receipt_number', models.CharField(max_length=32, null=True)),
                ('haraikomi_url', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.user_ticket')),
            ],
        ),

    ]
