# Generated by Django 3.2.9 on 2021-11-18 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_authorized_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_authorized_user',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eau', to='Event.events'),
        ),
        migrations.AlterField(
            model_name='events',
            name='private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='streaming_method',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='max_number_of_ticket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_of_issued_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='performance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Event.performance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='points_required',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
