# Generated by Django 3.2.9 on 2021-11-18 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20211118_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='Event.events'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='drawing_application_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
