# Generated by Django 3.2.9 on 2021-11-18 13:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0004_auto_20211118_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_purchase_history',
            old_name='user_ticket_id',
            new_name='user_ticket',
        ),
        migrations.RenameField(
            model_name='ticket_purchase_revervation',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='ticket_purchase_revervation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_elected', models.SmallIntegerField(choices=[(0, 'Not elected'), (1, 'Elected')], default=0)),
                ('is_purchased', models.SmallIntegerField(choices=[(0, 'Not purchased'), (1, 'Purchased')], default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 18, 13, 58, 22, 684663, tzinfo=utc))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drawing',
            },
        ),
    ]
