# Generated by Django 3.2.9 on 2021-11-20 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_auto_20211118_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
