# Generated by Django 3.2.9 on 2021-11-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_alter_drawing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
