# Generated by Django 3.2.9 on 2021-11-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterData', '0001_initial'),
        ('User', '0003_host_user_link_image_path_mgmt_portal_user_user_additional_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefecture_id',
            field=models.ForeignKey(blank=True, max_length=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.prefectures'),
        ),
    ]
