# Generated by Django 3.2.9 on 2021-11-15 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Point', '0001_initial'),
        ('User', '0002_auto_20211115_1403'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_profile_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device_token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('platform', models.SmallIntegerField(choices=[(1, 'IOS'), (2, 'Android')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255)),
                ('invalidated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.SmallIntegerField(choices=[(1, 'General user'), (2, 'Host user'), (3, 'Mgmt portal user')], default=1)),
                ('email', models.CharField(max_length=254)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_email', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not sent'), (1, 'Sent'), (2, 'Error')], default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Password_reset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.SmallIntegerField(choices=[(1, 'General user'), (2, 'Host user'), (3, 'Mgmt portal user')], default=1)),
                ('email', models.CharField(max_length=254)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('display_order', models.SmallIntegerField()),
                ('is_default', models.SmallIntegerField(choices=[(0, 'Not default'), (1, 'Default')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refresh_token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('mgmt_portal_user_id', models.IntegerField(null=True)),
                ('encrypted_refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField(auto_now_add=True)),
                ('is_blacklisted', models.SmallIntegerField(choices=[(0, 'Not blacklisted'), (2, 'Blacklisted')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sent_relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(null=True)),
                ('live_stream_id', models.IntegerField(null=True)),
                ('email_notification_trans_content_id', models.IntegerField(null=True)),
                ('push_notification_trans_content_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stamp_spending_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_for', models.SmallIntegerField(choices=[(1, 'Ticket')], default=1)),
                ('stamp_code_id', models.IntegerField(null=True)),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_stamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Stamp_receipt_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_stream_id', models.IntegerField(null=True)),
                ('stamp_code_id', models.IntegerField(null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_stamp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.user_stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Related_link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link_url', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('dir_path', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Push_notification_trans_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('internal_url', models.CharField(max_length=255, null=True)),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.IntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')])),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Push_notification_master_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_type', models.SmallIntegerField(choices=[(1, 'When a livestream event is created'), (2, 'When an office event is created'), (3, 'When a drawing winner determined'), (4, 'When a livestream starts in 10 minutes'), (5, 'When tickets purchase is complete'), (99, 'Any timing')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('internal_url', models.CharField(max_length=255, null=True)),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Push_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_platform', models.SmallIntegerField(choices=[(1, 'IOS'), (2, 'Android')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('internal_url', models.CharField(max_length=255, null=True)),
                ('scheduled_at', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Not sent'), (1, 'Sent')], default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email_notification_trans_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.SmallIntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')], default=1)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Email_notification_master_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_type', models.SmallIntegerField(choices=[(1, 'When a drawing winner determined'), (2, 'When tickets purchase is complete'), (99, 'Any timing')], default=1)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification_trans_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_type', models.IntegerField(choices=[(1, 'Host user'), (2, 'Client user (Mgmt portal user)'), (3, 'System admin user( Mgmt portal user)')], default=1)),
                ('from_user_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('to_user_ids', models.TextField(null=True)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.IntegerField(choices=[(0, 'Not delivered'), (1, 'Delivered')])),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification_master_content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timing_type', models.SmallIntegerField(choices=[(99, 'Any timing')], default=99)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('memo', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Box_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.SmallIntegerField(choices=[(0, 'Not read'), (1, 'Read')], default=1)),
                ('read_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_notification_master_content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.box_notification_master_content')),
                ('box_notification_trans_content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterData.box_notification_trans_content')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
